language: python
matrix:
  include:
    # - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
notifications:
  email:
  - yoav@yoavram.com
install:
- pip install click
- pip install nose
- pip install coverage
- pip install codecov
- pip install requests
- python setup.py install
script: nosetests tests --with-coverage --cover-package=ultrachronic
after_success:
- codecov
deploy:
  provider: pypi
  user: yoavram
  password:
    secure: e6MLF1GRqi72KvfId9p+AB2bPg9dTRzs9EmYQDxZ6fkyaAxtoCs/UuMbF306v9sl4GnXvuZEqXK7nTh1a2lnUrwdIDm54XSJ1WKlP9OfivqkObuhflEkX3aInne525NoQ1BJrsPcj3jkfWYcsQZpa3owCuUpVEA8aXbRD903dCaKnxinBHiFk1TgEnIRE11xYNJIff03VMpSzkqJ8swttB1PNCrlQhF/UMQy8yKqKjswtZC1LY5xJ05j8xWhpK6adlHTACnHx4Sw9YuGIOhvhlVED/e2ngKxHGKYNWS5whZ+PqpwLJcJbzgXes7loz4tFGY4Fmg6/7Qg6Bj7nbwsh48Alacve5H9TjFR3drUJPwGvZQmcQiGT3ImBhn5nrxkDav7UukoflNioaC1xEona2PM0q6mPMq5by0g/wtSqSsNyaULY6Lyz55zlw7LkCuhBYWS9wxKBfLLemwvussBX3LkEfcdHkFR/f2mZ7KgwW/+Rgkz77miwAfhZb6CFvPc5Q3gxztytGdM1ml5eyXOcGb5nI5lr0K1t8PgXdXrgy1lmZ2hX/ytFFsXLZ2C0znXZTIq+Jz+5F16RRB6BGL1emZRHqo6T97TB0R1BAVbnqmPAhnmgLRW0858YpaKfP7GqIVPBbd9aaRg3EEiSyxEM8wiMkadXBz/F1m+eEntjlY=
  skip_upload_docs: true
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: yoavram/ultrachronic
